name: firefly
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  bot_toast: 4.0.3
  pull_to_refresh: 2.0.0
  flutter_bloc: 8.1.2
  shared_preferences: 2.0.17
  one_context: 2.1.0
  equatable: 2.0.5
  dio: 4.0.0
  formz: 0.4.1
  g_json: 4.1.0
  dio_http_cache: 0.3.0
  flutter_svg: 2.0.5
  simple_gradient_text: 1.2.4
  rxdart: 0.27.7
  flutter_keyboard_visibility: 5.4.0
  cached_network_image: 3.2.3
  webview_flutter: 4.0.6
  flutter_switch: 0.3.2
  image_picker: 0.8.7+4
  permission_handler: 10.2.0
  file_picker: 5.2.7
  url_launcher: 6.1.10
  # note:  syncfusion_flutter is not free
  syncfusion_flutter_datepicker: 21.2.3
  syncfusion_flutter_core: 21.2.3
  textfield_tags: 2.0.2
  shimmer: 3.0.0
  image_cropper: 4.0.1
  flutter_colorpicker: 1.0.3
  image: 4.0.17
  numberpicker: 2.1.2
  dropdown_button2: 2.0.0
  flutter_slidable: 3.0.0
  in_app_review: 2.0.6
  exif: 3.0.0
  auto_size_text: 3.0.0
  intl: 0.18.0

  # Firebase
  firebase_core: 2.12.0
  firebase_messaging: 14.2.5
  firebase_auth: 4.2.9
  flutter_ffmpeg: 0.4.2
  camera: 0.10.5+2

  table_calendar: 3.0.9
  easy_localization: 3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

  face_camera:
    path: ./face_camera

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/font/
    - assets/images/
    - assets/translations/

  fonts:
    - family: SfProBold
      fonts:
        - asset: assets/font/SFPRODISPLAYBOLD.OTF
    - family: SfProMedium
      fonts:
        - asset: assets/font/SFPRODISPLAYMEDIUM.OTF
    - family: SfProRegular
      fonts:
        - asset: assets/font/SFPRODISPLAYREGULAR.OTF
    - family: LumanosimoRegular
      fonts:
        - asset: assets/font/LUMANOSIMO_REGULAR.ttf
